---
name: Commit Address Check
"on":
    push:
        branches:
            - master
jobs:
    commit-address-check:
        name: verify commit message contains wallet address
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Commit Address Checker
              id: Testing
              uses: git-consensus/github-action-verify-address@v1.2
