---
name: Coverage
"on":
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            MNEMONIC: ${{secrets.MNEMONIC}}
        steps:
            - name: Install nodegit dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y python2 python3 libkrb5-dev gcc openssl libssh2-1-dev libcurl4-openssl-dev g++ make
            - name: Check out the repo
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "14"
            - name: Install the Node.js dependencies
              run: npm i
            - name: Run Integration Test Coverage
              run: npm run coverage
